config: Exit on failure and report error.
Remove unused file site.conf from the list of configuration templates
(it is not around). Should a template failed to be deployed, abort
configuration and report error.

Change-Id: I6ef0d6911cd810c1ef88d19d89933e88f2ba44ff
Signed-off-by: Eric Chanudet <chanudete@ainfosec.com>

diff --git a/bin/cmds/config b/bin/cmds/config
--- a/bin/cmds/config
+++ b/bin/cmds/config
@@ -149,8 +149,11 @@ config_main() {
 
     mkdir -p "${CONF_DIR}"
 
-    for f in bblayers.conf local.conf openxt.conf build-manifest image-manifest site.conf; do
-        config_copy_template ${template} ${f}
+    for f in bblayers.conf local.conf openxt.conf build-manifest images-manifest; do
+        if ! config_copy_template ${template} ${f}; then
+            echo "ERROR: Failed to copy template file ${template}/${f} to ${CONF_DIR}."
+            exit 1
+        fi
     done
     config_generate_auto ${branch} ${sstate_dir}
 
